# Exported from Render on 2024-07-17T20:17:42Z
services:
- type: web
  name: useOnlineStudentApp
  runtime: node
  repo: https://github.com/JohnBatowei/useOnlineStudentApp
  branch: master
  plan: free
  envVars:
  - key: SECRET
    sync: false
  - key: studuent_app_online
    sync: false
  region: oregon
  buildCommand: yarn
  startCommand: yarn start
version: "1"
